# Data Processing Reference for a Single Stock - AARTIIND

This notebook processes stock price data and creates the following features:
- `rolling_avg_10`: 10-minute rolling average of close price
- `volume_sum_10`: Total volume traded over last 10 minutes
- `target`: Binary indicator if stock goes up (1) or down (0) in next 5 minutes

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
pwd

'/home/jupyter/22F1001871_IITMBS_MLOPS_OPPE1_MAY_2026'

## 1. Load Data

In [53]:

# Load data from file (for demonstration)
v01 = pd.read_csv("data/v0/AARTIIND__EQ__NSE__NSE__MINUTE.csv")
v02 = pd.read_csv("data/v0/ABCAPITAL__EQ__NSE__NSE__MINUTE.csv")

v11 = pd.read_csv("data/v1/ABFRL__EQ__NSE__NSE__MINUTE.csv")
v12 = pd.read_csv("data/v1/ADANIENT__EQ__NSE__NSE__MINUTE.csv")
v13 = pd.read_csv("data/v1/ADANIENT__EQ__NSE__NSE__MINUTE.csv")

# For loading from file, use:
# df = pd.read_csv('your_data.csv')

print("Data loaded successfully!")

Data loaded successfully!

## 2. Data Preprocessing

In [54]:
# Convert timestamp to datetime
v01['timestamp'] = pd.to_datetime(v01['timestamp'])
v02['timestamp'] = pd.to_datetime(v02['timestamp'])
v11['timestamp'] = pd.to_datetime(v11['timestamp'])
v12['timestamp'] = pd.to_datetime(v12['timestamp'])
v13['timestamp'] = pd.to_datetime(v13['timestamp'])

v01['stock_name'] = "AARTIIND"
v02['stock_name'] = "ABCAPITAL"

v11['stock_name'] = "ABFRL"
v12['stock_name'] = "ADANIENT"
v13['stock_name'] = "ADANIGAS"

# Sort by timestamp (important for time series operations)
v01 = v01.sort_values('timestamp').reset_index(drop=True)
v02 = v01.sort_values('timestamp').reset_index(drop=True)

v11 = v01.sort_values('timestamp').reset_index(drop=True)
v12 = v01.sort_values('timestamp').reset_index(drop=True)
v13 = v01.sort_values('timestamp').reset_index(drop=True)

# Set timestamp as index for easier time-based operations
v01.set_index('timestamp', inplace=True)
v02.set_index('timestamp', inplace=True)

v11.set_index('timestamp', inplace=True)
v12.set_index('timestamp', inplace=True)
v13.set_index('timestamp', inplace=True)

v01.to_csv("data/v0/AARTIIND__processed.csv")
v02.to_csv("data/v0/ABCAPITAL__processed.csv")
v11.to_csv("data/v1/ABFRL__processed.csv")
v12.to_csv("data/v1/ADANIENT__processed.csv")
v13.to_csv("data/v1/ADANIGAS__processed.csv")

print("Data preprocessed!")
print(f"Date range: {v01.index.min()} to {v01.index.max()}")
v01.head()

Data preprocessed!
Date range: 2017-01-02 09:15:00+05:30 to 2021-01-01 15:29:00+05:30

                            open   high    low  close  volume stock_name
timestamp
2017-01-02 09:15:00+05:30  340.0  340.0  340.0  340.0    11.0   AARTIIND
2017-01-02 09:16:00+05:30  340.0  340.0  340.0  340.0     0.0   AARTIIND
2017-01-02 09:17:00+05:30  340.0  340.0  340.0  340.0     0.0   AARTIIND
2017-01-02 09:18:00+05:30  340.0  343.7  340.0  343.7     1.0   AARTIIND
2017-01-02 09:19:00+05:30  343.7  343.7  343.7  343.7     1.0   AARTIIND

In [55]:
# Fill missing values with prior values (forward fill)
v01.ffill(inplace=True)
v02.ffill(inplace=True)

v11.ffill(inplace=True)
v12.ffill(inplace=True)
v13.ffill(inplace=True)

# Check for missing values after filling
print("Missing values after filling:")
print(v01.isnull().sum())
print(v02.isnull().sum())
print(v11.isnull().sum())
print(v12.isnull().sum())
print(v13.isnull().sum())

Missing values after filling:
open          0
high          0
low           0
close         0
volume        0
stock_name    0
dtype: int64
open          0
high          0
low           0
close         0
volume        0
stock_name    0
dtype: int64
open          0
high          0
low           0
close         0
volume        0
stock_name    0
dtype: int64
open          0
high          0
low           0
close         0
volume        0
stock_name    0
dtype: int64
open          0
high          0
low           0
close         0
volume        0
stock_name    0
dtype: int64

## 3. Feature Engineering

In [56]:
# Feature 1: 10-minute rolling average of close price
# Using window='10T' for 10 minutes
v01['rolling_avg_10'] = v01['close'].rolling(window='10min', min_periods=1).mean()
v02['rolling_avg_10'] = v02['close'].rolling(window='10min', min_periods=1).mean()

v11['rolling_avg_10'] = v11['close'].rolling(window='10min', min_periods=1).mean()
v12['rolling_avg_10'] = v12['close'].rolling(window='10min', min_periods=1).mean()
v13['rolling_avg_10'] = v13['close'].rolling(window='10min', min_periods=1).mean()

# Feature 2: Total volume traded over last 10 minutes
v01['volume_sum_10'] = v01['volume'].rolling(window='10min', min_periods=1).sum()
v02['volume_sum_10'] = v02['volume'].rolling(window='10min', min_periods=1).sum()
v11['volume_sum_10'] = v11['volume'].rolling(window='10min', min_periods=1).sum()
v12['volume_sum_10'] = v12['volume'].rolling(window='10min', min_periods=1).sum()
v13['volume_sum_10'] = v13['volume'].rolling(window='10min', min_periods=1).sum()


print("Rolling features created!")
v01[['close', 'volume', 'rolling_avg_10', 'volume_sum_10']].head(5)
v02[['close', 'volume', 'rolling_avg_10', 'volume_sum_10']].head(5)
v11[['close', 'volume', 'rolling_avg_10', 'volume_sum_10']].head(5)
v12[['close', 'volume', 'rolling_avg_10', 'volume_sum_10']].head(5)
v13[['close', 'volume', 'rolling_avg_10', 'volume_sum_10']].head(5)

Rolling features created!

                           close  volume  rolling_avg_10  volume_sum_10
timestamp
2017-01-02 09:15:00+05:30  340.0    11.0         340.000           11.0
2017-01-02 09:16:00+05:30  340.0     0.0         340.000           11.0
2017-01-02 09:17:00+05:30  340.0     0.0         340.000           11.0
2017-01-02 09:18:00+05:30  343.7     1.0         340.925           12.0
2017-01-02 09:19:00+05:30  343.7     1.0         341.480           13.0

In [57]:
# Remove rows where rolling_avg_10 or volume_sum_10 is NaN
v01.dropna(subset=['rolling_avg_10', 'volume_sum_10'], inplace=True)
v02.dropna(subset=['rolling_avg_10', 'volume_sum_10'], inplace=True)
v11.dropna(subset=['rolling_avg_10', 'volume_sum_10'], inplace=True)
v12.dropna(subset=['rolling_avg_10', 'volume_sum_10'], inplace=True)
v13.dropna(subset=['rolling_avg_10', 'volume_sum_10'], inplace=True)

print("Removed rows with NaN in rolling_avg_10 or volume_sum_10.")
print(f"New shape: {v01.shape}")

Removed rows with NaN in rolling_avg_10 or volume_sum_10.
New shape: (370458, 8)

In [58]:
# Feature 3: Target variable - does stock go up in next 5 minutes?
# Shift close price backwards by 5 minutes to get future price
v01['close_5min_future'] = v01['close'].shift(-5)
v02['close_5min_future'] = v02['close'].shift(-5)

v11['close_5min_future'] = v11['close'].shift(-5)
v12['close_5min_future'] = v12['close'].shift(-5)
v13['close_5min_future'] = v13['close'].shift(-5)

# Create binary target: 1 if price goes up, 0 if it goes down or stays same
v01['target'] = (v01['close_5min_future'] > v01['close']).astype(int)
v02['target'] = (v02['close_5min_future'] > v02['close']).astype(int)

v11['target'] = (v11['close_5min_future'] > v11['close']).astype(int)
v12['target'] = (v12['close_5min_future'] > v12['close']).astype(int)
v13['target'] = (v13['close_5min_future'] > v13['close']).astype(int)



print("Target variable created!")
print(f"\nTarget distribution:")
print(v01['target'].value_counts())
print(f"\nTarget ratio (up/total): {v01['target'].mean():.2%}")

Target variable created!

Target distribution:
target
0    207960
1    162498
Name: count, dtype: int64

Target ratio (up/total): 43.86%

## 5. Final Dataset

In [59]:
# Drop close_5min_future as its a signal to target variable
v01.drop(["close_5min_future"],axis=1,inplace=True)
v02.drop(["close_5min_future"],axis=1,inplace=True)

v11.drop(["close_5min_future"],axis=1,inplace=True)
v12.drop(["close_5min_future"],axis=1,inplace=True)
v13.drop(["close_5min_future"],axis=1,inplace=True)


# Drop rows where target is NaN
v01_clean = v01.dropna(subset=['target']).copy()
v02_clean = v02.dropna(subset=['target']).copy()

v11_clean = v11.dropna(subset=['target']).copy()
v12_clean = v12.dropna(subset=['target']).copy()
v13_clean = v13.dropna(subset=['target']).copy()

# Take the last 20 observations for the test set
v0 = pd.concat([v01, v02])
v1 = pd.concat([v01, v02, v11, v12, v13])

test_v0 = v0.tail(20).copy()
test_v1 = v1.tail(20).copy()

# Remove the test observations from the training set
train_v0 = v0.iloc[:-20].copy()
train_v1 = v1.iloc[:-20].copy()


print(f"\nTest dataset (last 20 observations):")
print(f"Shape: {test_v0.shape}")
print(f"\nClean dataset (removed last 20 observations for test):")
print(f"Shape: {train_v1.shape}")

Test dataset (last 20 observations):
Shape: (20, 9)

Clean dataset (removed last 20 observations for test):
Shape: (1852270, 9)

## 7. Export Processed Data

In [62]:
# -----------------------------
# Save Iteration 1 (v0)
# -----------------------------
train_v0_file = "train_v0.csv"
test_v0_file = "test_v0.csv"

train_v0.to_csv(train_v0_file)
test_v0.to_csv(test_v0_file)

print(f"Processed v0 training data saved to: {train_v0_file}")
print(f"Processed v0 test data saved to: {test_v0_file}")

print("\n===== v0 Dataset Summary =====")
print(f"Training Columns : {list(train_v0.columns)}")
print(f"Training Rows    : {len(train_v0)}")
print(f"Test Columns     : {list(test_v0.columns)}")
print(f"Test Rows        : {len(test_v0)}")


# -----------------------------
# Save Iteration 2 (v1)
# -----------------------------
train_v1_file = "train_v1.csv"
test_v1_file = "test_v1.csv"

test_v1.to_csv(train_v1_file)
test_v1.to_csv(test_v1_file)

print(f"\nProcessed v1 training data saved to: {train_v1_file}")
print(f"Processed v1 test data saved to: {test_v1_file}")

print("\n===== v1 Dataset Summary =====")
print(f"Training Columns : {list(train_v1.columns)}")
print(f"Training Rows    : {len(train_v1)}")
print(f"Test Columns     : {list(test_v1.columns)}")
print(f"Test Rows        : {len(test_v1)}")

Processed v0 training data saved to: train_v0.csv
Processed v0 test data saved to: test_v0.csv

===== v0 Dataset Summary =====
Training Columns : ['open', 'high', 'low', 'close', 'volume', 'stock_name', 'rolling_avg_10', 'volume_sum_10', 'target']
Training Rows    : 740896
Test Columns     : ['open', 'high', 'low', 'close', 'volume', 'stock_name', 'rolling_avg_10', 'volume_sum_10', 'target']
Test Rows        : 20

Processed v1 training data saved to: train_v1.csv
Processed v1 test data saved to: test_v1.csv

===== v1 Dataset Summary =====
Training Columns : ['open', 'high', 'low', 'close', 'volume', 'stock_name', 'rolling_avg_10', 'volume_sum_10', 'target']
Training Rows    : 1852270
Test Columns     : ['open', 'high', 'low', 'close', 'volume', 'stock_name', 'rolling_avg_10', 'volume_sum_10', 'target']
Test Rows        : 20

In [64]:
data = pd.read_csv("train_v1.csv")
dat

,timestamp,open,high,low,close,volume,stock_name,rolling_avg_10,volume_sum_10,target
0,2021-01-01 15:10:00+05:30,1262.00,1262.15,1260.9,1260.90,763.0,AARTIIND,1262.040,9991.0,0
1,2021-01-01 15:11:00+05:30,1260.90,1262.00,1259.6,1259.80,4316.0,AARTIIND,1261.920,13187.0,1
2,2021-01-01 15:12:00+05:30,1259.80,1262.00,1258.4,1260.95,2131.0,AARTIIND,1261.815,14165.0,1
3,2021-01-01 15:13:00+05:30,1260.95,1260.95,1260.5,1260.50,393.0,AARTIIND,1261.665,14117.0,1
4,2021-01-01 15:14:00+05:30,1260.50,1260.90,1260.0,1260.70,742.0,AARTIIND,1261.390,13663.0,0

In [65]:
test_v1_file = "test_v1.csv"
test_v1.to_csv(test_v1_file)
print(f"Processed v1 test data saved to: {test_v1_file}")
print(f"Test Columns     : {list(test_v1.columns)}")
print(f"Test Rows        : {len(test_v1)}")

Processed v1 test data saved to: test_v1.csv
Test Columns     : ['open', 'high', 'low', 'close', 'volume', 'stock_name', 'rolling_avg_10', 'volume_sum_10', 'target']
Test Rows        : 20

In [70]:
train_v0.to_parquet("data/train_v0.parquet", index=False)
train_v1.to_parquet("data/train_v1.parquet", index=False)

test_v0.to_parquet("data/test_v0.parquet", index=False)
test_v1.to_parquet("data/test_v1.parquet", index=False)